### ISSUE TITLE
Write docs/advanced

### ISSUE THREAD

**Issue by michaelsena** [ceramicnetwork/docs#179]
- Advanced:
      - index.md
      - Standards: 
        - docs/advanced/standards/index.md
        - Stream program standards:
          - docs/advanced/standards/stream-programs/index.md
          - CIP-3 JSON Storage (TileDocument): index.md
          - CIP-17 Crypto Account Links (CAIP10Link): index.md
        - Application standards:
          - docs/advanced/standards/application-protocols/index.md
          - CIP-11 Account-based indexing (IDX): docs/advanced/standards/application-protocols/cip-11-account-based-stream- indexing.md
        - Data model standards:
          - docs/advanced/standards/data-models/index.md
          - Data model universe: index.md
          - Data model examples and patterns: index.md
        - Account standards:
          - CIP-4 3ID DID: authentication/3id-did/method.md
          - PKH DID: index.md
          - Key DID: authentication/key-did/method.md
          - CIP-40 NFT DID: authentication/nft-did/method.md
          - CIP-50 Safe DID: authentication/safe-did/method.md
      - Indexing: docs/advanced/indexing.md
      - Storage and backup: docs/advanced/storage-and-backup.md
      - Privacy and access control: docs/advanced/privacy-and-access-control.md

**Comment by glcohen** [comment]
@michaelsena to break into a few stories
