### ISSUE TITLE
Update "hosting a node" page to use go-ipfs

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/docs#191]
* Remove instructions on using `@ceramicnetwork/ipfs-daemon` package
* Remove distinction about in-process vs out-of-process ipfs
* Include how to set up go-ipfs node with dag-jose support.
* Include link to js-ipfs -> go-ipfs migration guide from https://github.com/ceramicnetwork/docs/issues/192

**Comment by decentralgabe** [comment]
duplicate of https://github.com/3box/ceramic-infra/issues/504
