### ISSUE TITLE
Document how to subscribe to updates on a stream

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/docs#95]
There are 2 things that should be covered.

1)
When you load a Stream the content won't change by default - the handle you get has the state as of the point in time when it was loaded. But if you call `.subscribe()` on it, then the Stream handle will get subscribe to updates to the underlying log, and the contents within the Stream object can change over time

2)
Some examples on how an app can subscribe to changes to a stream and take action on each new update.  This is a little bit complicated/confusing right now because Stream is an Observable of StreamState, which means that if you subscribe to it the updates you get have a new StreamState object which is fairly low level and most devs won't know what to do with it. I wonder if we should try to change this so that Stream is an Observable of new Stream objects each tied to the point in time of each new state?  So then app code could call subscribe() with a callback that gets a new Stream object each time, which will be more what they are accustomed to dealing with

**Comment by stbrody** [comment]
FYI @michaelsena, I think number 1 above could be done right away, and is probably useful content to get out there.  Number 2 might want to wait until we think more about what the best API should be for devs to do this

**Comment by stbrody** [comment]
@ukstv I'd be interested in your thoughts on what I wrote for number 2 above.  It seems like subscribing to updates on a stream will be a common use case that we want to make simple and clear how to do, without needing to understand Ceramic internals like the state object

**Comment by michaelsena** [comment]
I like the idea of a simple callback that is easy to add to your
application logic.

**Comment by michaelsena** [comment]
Spencer where do you think we should add #1 to the docs? As a new page in
the install section between queries and pinning?

**Comment by michaelsena** [comment]
Or best integrated into each pace?

**Comment by stbrody** [comment]
Hmm... I think for now just putting it on the Queries page is probably fine.

Longer term we may want a "Streams" page somewhere that talks about the common functionality shared across all stream types

**Comment by ukstv** [comment]
@stbrody I believe the intent is good. Exposing something other that raw StreamState would lose certain composability we have though. If full blown Stream instance is exposed, it would lead to confusion also: some methods change the state. A way to go that I see is providing some sort of per-stream-type read-only wrapper, that can be plugged on demand, i.e. via rxjs `map` operator. Say, for Tile, that would expose only read-only methods. In my mind that could look like this:

```
import {TileDocument, asTileSnap} from '@ceramicnetwork/tile-stream'

const document = await TileDocument.load(...)
// Dump content on each update
document.pipe(map(asTileSnap)).subscribe(snap => {
  console.log(snap.content)
})
```

This way, one should also take care of having same read-only interface for both TileDocument and snap instances.

**Comment by ukstv** [comment]
One could further simplify this by adding an explicit `snap` method that returns an `Observable<TileSnap>`:

```
// TileDocument definition
snap(): Observable<TileSnap> {
  return this.pipe(map(asTileSnap))
}
```

**Comment by ukstv** [comment]
Or maybe `live` is a better name than `snap`:
```
document.live.subscribe(snap => {
  console.log(snap.content)
})
```

**Comment by stbrody** [comment]
Thanks for the ideas @ukstv. I added https://www.notion.so/threebox/Simple-API-to-subscribe-to-stream-updates-ea4aece4341e44b0bdca0bb0b32b1f35 to track this
